version: '3'

services:

    php:
        build: docker/php
        volumes:
            - "./:/project"
            - "./.composer:/home/project/.composer"
        depends_on:
            - mysql

    nginx:
        build: docker/nginx
        volumes:
            - "./:/project:cached"
        depends_on:
            - php

    mysql:
        build: docker/mysql
        volumes:
            - "./data:/var/lib/mysql/"
        ports:
            - "3306:3306"
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_USER=project"
            - "MYSQL_PASSWORD=project"
            - "MYSQL_DATABASE=project"
